//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceApp.Server.Repositories.MSSql.Queries.Address {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AddressQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AddressQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InvoiceApp.Server.Repositories.MSSql.Queries.Address.AddressQueries", typeof(AddressQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Addresses (City, Country, Street, Number, FlatNumber, PostCode)
        ///	VALUES (@CITY, @COUNTRY, @STREET, @NUMBER, @FLATNUMBER, @POSTCODE).
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM Addresses WHERE AddressId = @ADDRESSID.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        /// AddressId AS ADDRESSID, 
        ///  City AS CITY, 
        ///  Country AS COUNTRY, 
        ///  Street AS STREET, 
        ///  Number AS NUMBER, 
        ///  FlatNumber AS FLATNUMBER, 
        ///  PostCode AS POSTCODE 
        ///FROM 
        ///  Addresses.
        /// </summary>
        internal static string GET {
            get {
                return ResourceManager.GetString("GET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        /// AddressId AS ADDRESSID, 
        ///  City AS CITY, 
        ///  Country AS COUNTRY, 
        ///  Street AS STREET, 
        ///  Number AS NUMBER, 
        ///  FlatNumber AS FLATNUMBER, 
        ///  PostCode AS POSTCODE 
        ///FROM 
        ///  Addresses 
        ///WHERE 
        ///  AddressId = @ADDRESSID.
        /// </summary>
        internal static string GetById {
            get {
                return ResourceManager.GetString("GetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE 
        ///  Addresses 
        ///SET 
        ///  City = @CITY, 
        ///  Country = @COUNTRY, 
        ///  Street = @STREET, 
        ///  Number = @NUMBER, 
        ///  FlatNumber = @FLATNUMBER, 
        ///  PostCode = @POSTCODE 
        ///WHERE 
        ///  AddressId = AddressId.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
    }
}
